name: smooth_transition
description: "A simple and customizable Flutter package for smooth page transition animations,
  including fade, slide, and scale effects. Easy to use with Navigator.push()."

publish_to: 'none' 

version: 1.0.3

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  smooth_transition:
    path: package/smooth_transition
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

